services:
  # Nextcloud Application
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT}:80"
    depends_on:
      - nextcloud-db
    environment:
      - MYSQL_HOST=${NEXTCLOUD_DB_HOST}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud_data:/var/www/html

  # MariaDB for Nextcloud
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud_db_data:/var/lib/mysql

  # NGINX Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    depends_on:
      - npm-db
    ports:
      - "${NPM_HTTP_PORT}:80"
      - "${NPM_UI_PORT}:81"
      - "${NPM_HTTPS_PORT}:443"
    environment:
      DB_MYSQL_HOST: ${NPM_DB_HOST}
      DB_MYSQL_PORT: ${NPM_DB_PORT}
      DB_MYSQL_USER: ${NPM_DB_USER}
      DB_MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      DB_MYSQL_NAME: ${NPM_DB_NAME}
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  # MariaDB for NGINX Proxy Manager
  npm-db:
    image: mariadb
    container_name: npm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${NPM_DB_PASSWORD}
      - MYSQL_DATABASE=${NPM_DB_NAME}
      - MYSQL_USER=${NPM_DB_USER}
      - MYSQL_PASSWORD=${NPM_DB_PASSWORD}
    volumes:
      - npm_db_data:/var/lib/mysql

volumes:
  nextcloud_data:
  nextcloud_db_data:
  npm_data:
  npm_letsencrypt:
  npm_db_data:
